# Generated by Django 4.2.1 on 2023-05-06 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
                ('monday', models.BooleanField(default=True)),
                ('availability_monday_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('availability_monday_end_time', models.TimeField(default=datetime.datetime(2023, 5, 6, 20, 51, 32, 688055, tzinfo=datetime.timezone.utc))),
                ('tuesday', models.BooleanField(default=True)),
                ('availability_tuesday_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('availability_tuesday_end_time', models.TimeField(default=datetime.datetime(2023, 5, 6, 20, 51, 32, 688055, tzinfo=datetime.timezone.utc))),
                ('wednesday', models.BooleanField(default=True)),
                ('availability_wednesday_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('availability_wednesday_end_time', models.TimeField(default=datetime.datetime(2023, 5, 6, 20, 51, 32, 688055, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='GeneralDiagnosticQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'GeneralDiagnosticQuestions',
                'verbose_name_plural': 'GeneralDiagnosticQuestionss',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(default=dict)),
                ('health_data', models.JSONField(default=dict)),
                ('extra_data', models.JSONField(default=dict)),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('appointment_duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('meeting_link', models.URLField(default='https://meet.google.com')),
                ('files', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='filer.file')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.JSONField(default=dict, verbose_name='feedback')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
