# Generated by Django 4.2.1 on 2023-05-06 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaldiagnosticquestions',
            options={'verbose_name': 'General Diagnostic Questions', 'verbose_name_plural': 'General Diagnostic Questions'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_monday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 6, 21, 31, 23, 442181, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_tuesday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 6, 21, 31, 23, 442181, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_wednesday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 6, 21, 31, 23, 442181, tzinfo=datetime.timezone.utc)),
        ),
    ]
