# Generated by Django 4.2.1 on 2023-05-06 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_doctor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_monday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 6, 23, 29, 31, 15123, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_tuesday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 6, 23, 29, 31, 15123, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_wednesday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 6, 23, 29, 31, 15123, tzinfo=datetime.timezone.utc)),
        ),
    ]
