# Generated by Django 4.2.1 on 2023-05-06 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_doctor_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_monday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 7, 3, 58, 34, 756826, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_tuesday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 7, 3, 58, 34, 756826, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability_wednesday_end_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 7, 3, 58, 34, 756826, tzinfo=datetime.timezone.utc)),
        ),
    ]
