# Generated by Django 4.2.1 on 2023-05-06 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines', models.JSONField(default=dict)),
                ('doses', models.JSONField(default=dict)),
                ('next_checkup_date', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 16, 51, 32, 691670, tzinfo=datetime.timezone.utc))),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
    ]
