# Generated by Django 4.2.1 on 2023-05-06 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='next_checkup_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 17, 31, 23, 442181, tzinfo=datetime.timezone.utc)),
        ),
    ]
