# Generated by Django 4.2.1 on 2023-05-06 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_prescription_next_checkup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='next_checkup_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 18, 23, 17, 229902, tzinfo=datetime.timezone.utc)),
        ),
    ]
